### ISSUE TITLE
Stacked histos

### ISSUE THREAD

**Issue by ghost** [kgryte/data#1]
Need to create stacked histogram for figure 2 or 3.

This seems the best option to give overall picture of what we see. 

Quick play with .json file to convert to mat file and plot is easy but don't know what data this is...

I do not have the code that tells me how the data ID is encrypted. 

Other options are figure with stacked individual molecule histogram - less intuitive; or stacked MVA plots, again less intuitive.

Can you help with this?

Since this data is sorted and clean ideally I want to use this for the stacked histos. otherwise I will have to use the Seneca data I have on my PC.

**Comment by kgryte** [comment]
Yes, I can help with this. Regarding *.json to *.mat file conversion, I suggest creating the figures directly as SVG. See my d3-chart-generators repository for examples. I will be releasing more generators shortly. Regarding the encryption, I will forward this script along to you so that you have this again in your possession.
